using System;
using System.Collections.Generic;
using System.Linq;
using EpsgCoordinateSystems.Nad83UsFt;

namespace EpsgCoordinateSystems
{
    public static class Nad83StatePlaneUsFt
    {
        public static IEnumerable<string> Names => typeof(Nad83StatePlaneUsFt).GetFields().Select(x => x.Name);
        public static IEpsgCoordinateSystem ArkansasNorth => new NAD83_Arkansas_North_ftUS();
        public static IEpsgCoordinateSystem ArkansasSouth => new NAD83_Arkansas_South_ftUS();
        public static IEpsgCoordinateSystem Blm14N => new NAD83_BLM_14N_ftUS();
        public static IEpsgCoordinateSystem Blm15N => new NAD83_BLM_15N_ftUS();
        public static IEpsgCoordinateSystem Blm16N => new NAD83_BLM_16N_ftUS();
        public static IEpsgCoordinateSystem Blm17N => new NAD83_BLM_17N_ftUS();
        public static IEpsgCoordinateSystem CaliforniaZone1 => new NAD83_California_zone_1_ftUS();
        public static IEpsgCoordinateSystem CaliforniaZone2 => new NAD83_California_zone_2_ftUS();
        public static IEpsgCoordinateSystem CaliforniaZone3 => new NAD83_California_zone_3_ftUS();
        public static IEpsgCoordinateSystem CaliforniaZone4 => new NAD83_California_zone_4_ftUS();
        public static IEpsgCoordinateSystem CaliforniaZone5 => new NAD83_California_zone_5_ftUS();
        public static IEpsgCoordinateSystem CaliforniaZone6 => new NAD83_California_zone_6_ftUS();
        public static IEpsgCoordinateSystem ColoradoCentral => new NAD83_Colorado_Central_ftUS();
        public static IEpsgCoordinateSystem ColoradoNorth => new NAD83_Colorado_North_ftUS();
        public static IEpsgCoordinateSystem ColoradoSouth => new NAD83_Colorado_South_ftUS();
        public static IEpsgCoordinateSystem Connecticut => new NAD83_Connecticut_ftUS();
        public static IEpsgCoordinateSystem Delaware => new NAD83_Delaware_ftUS();
        public static IEpsgCoordinateSystem FloridaEast => new NAD83_Florida_East_ftUS();
        public static IEpsgCoordinateSystem FloridaNorth => new NAD83_Florida_North_ftUS();
        public static IEpsgCoordinateSystem FloridaWest => new NAD83_Florida_West_ftUS();
        public static IEpsgCoordinateSystem GeorgiaEast => new NAD83_Georgia_East_ftUS();
        public static IEpsgCoordinateSystem GeorgiaWest => new NAD83_Georgia_West_ftUS();
        public static IEpsgCoordinateSystem HawaiiZone3 => new NAD83_Hawaii_zone_3_ftUS();
        public static IEpsgCoordinateSystem IdahoCentral => new NAD83_Idaho_Central_ftUS();
        public static IEpsgCoordinateSystem IdahoEast => new NAD83_Idaho_East_ftUS();
        public static IEpsgCoordinateSystem IdahoWest => new NAD83_Idaho_West_ftUS();
        public static IEpsgCoordinateSystem IllinoisEast => new NAD83_Illinois_East_ftUS();
        public static IEpsgCoordinateSystem IllinoisWest => new NAD83_Illinois_West_ftUS();
        public static IEpsgCoordinateSystem IndianaEast => new NAD83_Indiana_East_ftUS();
        public static IEpsgCoordinateSystem IndianaWest => new NAD83_Indiana_West_ftUS();
        public static IEpsgCoordinateSystem KentuckyNorth => new NAD83_Kentucky_North_ftUS();
        public static IEpsgCoordinateSystem KentuckySingleZone => new NAD83_Kentucky_Single_Zone_ftUS();
        public static IEpsgCoordinateSystem KentuckySouth => new NAD83_Kentucky_South_ftUS();
        public static IEpsgCoordinateSystem LouisianaNorth => new NAD83_Louisiana_North_ftUS();
        public static IEpsgCoordinateSystem LouisianaOffshore => new NAD83_Louisiana_Offshore_ftUS();
        public static IEpsgCoordinateSystem LouisianaSouth => new NAD83_Louisiana_South_ftUS();
        public static IEpsgCoordinateSystem MaineEast => new NAD83_Maine_East_ftUS();
        public static IEpsgCoordinateSystem MaineWest => new NAD83_Maine_West_ftUS();
        public static IEpsgCoordinateSystem Maryland => new NAD83_Maryland_ftUS();
        public static IEpsgCoordinateSystem MassachusettsIsland => new NAD83_Massachusetts_Island_ftUS();
        public static IEpsgCoordinateSystem MassachusettsMainland => new NAD83_Massachusetts_Mainland_ftUS();
        public static IEpsgCoordinateSystem MinnesotaCentral => new NAD83_Minnesota_Central_ftUS();
        public static IEpsgCoordinateSystem MinnesotaNorth => new NAD83_Minnesota_North_ftUS();
        public static IEpsgCoordinateSystem MinnesotaSouth => new NAD83_Minnesota_South_ftUS();
        public static IEpsgCoordinateSystem MississippiEast => new NAD83_Mississippi_East_ftUS();
        public static IEpsgCoordinateSystem MississippiWest => new NAD83_Mississippi_West_ftUS();
        public static IEpsgCoordinateSystem Nebraska => new NAD83_Nebraska_ftUS();
        public static IEpsgCoordinateSystem NewHampshire => new NAD83_New_Hampshire_ftUS();
        public static IEpsgCoordinateSystem NewMexicoCentral => new NAD83_New_Mexico_Central_ftUS();
        public static IEpsgCoordinateSystem NewMexicoEast => new NAD83_New_Mexico_East_ftUS();
        public static IEpsgCoordinateSystem NewMexicoWest => new NAD83_New_Mexico_West_ftUS();
        public static IEpsgCoordinateSystem NewYorkCentral => new NAD83_New_York_Central_ftUS();
        public static IEpsgCoordinateSystem NewYorkEast => new NAD83_New_York_East_ftUS();
        public static IEpsgCoordinateSystem NewYorkLongIsland => new NAD83_New_York_Long_Island_ftUS();
        public static IEpsgCoordinateSystem NewYorkWest => new NAD83_New_York_West_ftUS();
        public static IEpsgCoordinateSystem NorthCarolina => new NAD83_North_Carolina_ftUS();
        public static IEpsgCoordinateSystem OhioNorth => new NAD83_Ohio_North_ftUS();
        public static IEpsgCoordinateSystem OhioSouth => new NAD83_Ohio_South_ftUS();
        public static IEpsgCoordinateSystem OklahomaNorth => new NAD83_Oklahoma_North_ftUS();
        public static IEpsgCoordinateSystem OklahomaSouth => new NAD83_Oklahoma_South_ftUS();
        public static IEpsgCoordinateSystem PennsylvaniaNorth => new NAD83_Pennsylvania_North_ftUS();
        public static IEpsgCoordinateSystem PennsylvaniaSouth => new NAD83_Pennsylvania_South_ftUS();
        public static IEpsgCoordinateSystem RhodeIsland => new NAD83_Rhode_Island_ftUS();
        public static IEpsgCoordinateSystem SouthDakotaNorth => new NAD83_South_Dakota_North_ftUS();
        public static IEpsgCoordinateSystem SouthDakotaSouth => new NAD83_South_Dakota_South_ftUS();
        public static IEpsgCoordinateSystem Tennessee => new NAD83_Tennessee_ftUS();
        public static IEpsgCoordinateSystem TexasCentral => new NAD83_Texas_Central_ftUS();
        public static IEpsgCoordinateSystem TexasNorthCentral => new NAD83_Texas_North_Central_ftUS();
        public static IEpsgCoordinateSystem TexasNorth => new NAD83_Texas_North_ftUS();
        public static IEpsgCoordinateSystem TexasSouthCentral => new NAD83_Texas_South_Central_ftUS();
        public static IEpsgCoordinateSystem TexasSouth => new NAD83_Texas_South_ftUS();
        public static IEpsgCoordinateSystem UtahCentral => new NAD83_Utah_Central_ftUS();
        public static IEpsgCoordinateSystem UtahNorth => new NAD83_Utah_North_ftUS();
        public static IEpsgCoordinateSystem UtahSouth => new NAD83_Utah_South_ftUS();
        public static IEpsgCoordinateSystem VirginiaNorth => new NAD83_Virginia_North_ftUS();
        public static IEpsgCoordinateSystem VirginiaSouth => new NAD83_Virginia_South_ftUS();
        public static IEpsgCoordinateSystem WashingtonNorth => new NAD83_Washington_North_ftUS();
        public static IEpsgCoordinateSystem WashingtonSouth => new NAD83_Washington_South_ftUS();
        public static IEpsgCoordinateSystem WestVirginiaNorth => new NAD83_West_Virginia_North_ftUS();
        public static IEpsgCoordinateSystem WestVirginiaSouth => new NAD83_West_Virginia_South_ftUS();
        public static IEpsgCoordinateSystem WisconsinCentral => new NAD83_Wisconsin_Central_ftUS();
        public static IEpsgCoordinateSystem WisconsinNorth => new NAD83_Wisconsin_North_ftUS();
        public static IEpsgCoordinateSystem WisconsinSouth => new NAD83_Wisconsin_South_ftUS();
        public static IEpsgCoordinateSystem WyomingEastCentral => new NAD83_Wyoming_East_Central_ftUS();
        public static IEpsgCoordinateSystem WyomingEast => new NAD83_Wyoming_East_ftUS();
        public static IEpsgCoordinateSystem WyomingWestCentral => new NAD83_Wyoming_West_Central_ftUS();
        public static IEpsgCoordinateSystem WyomingWest => new NAD83_Wyoming_West_ftUS();
    }
}